<a href="https://colab.research.google.com/github/koolgax99/predicting-genetic-disorders/blob/main/predicting_genetic_disorders.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
train = pd.read_csv('/content/train_genetic_disorders.csv')
test = pd.read_csv('/content/test_genetic_disorders.csv')
train.head()

  Patient Id  ...                    Disorder Subclass
0  PID0x6418  ...  Leber's hereditary optic neuropathy
1  PID0x25d5  ...                      Cystic fibrosis
2  PID0x4a82  ...                             Diabetes
3  PID0x4ac8  ...                       Leigh syndrome
4  PID0x1bf7  ...                               Cancer

[5 rows x 45 columns]

In [ ]:
train.describe()

        Patient Age  Blood cell count (mcL)  ...     Symptom 4     Symptom 5
count  19643.000000            21011.000000  ...  18987.000000  18956.000000
mean       6.974851                4.899004  ...      0.497393      0.460804
std        4.322584                0.199829  ...      0.500006      0.498474
min        0.000000                4.092727  ...      0.000000      0.000000
25%        3.000000                4.763230  ...      0.000000      0.000000
50%        7.000000                4.899548  ...      0.000000      0.000000
75%       11.000000                5.033977  ...      1.000000      1.000000
max       14.000000                5.609829  ...      1.000000      1.000000

[8 rows x 16 columns]